---
cam0:
    camera_model: radtan
    T_cam_imu:
        - [0.0148655429818, 0.999557249008, -0.0257744366974, 0.0652229095355]
        - [-0.999880929699, 0.0149672133247, 0.00375618835797, -0.0207063854927]
        - [0.00414029679422, 0.025715529948, 0.999660727178, -0.00805460246003]
        - [0.0, 0.0, 0.0, 1.0]
    distortion_coeffs: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]
    intrinsics:
        - [458.654, 0.0, 367.215]
        - [0.0, 457.296, 248.375]
        - [0.0, 0.0, 1.0]

# 图像与特征跟踪
rows: 480
cols: 752
per_grid_rows: 40
per_grid_cols: 50
edge_x: 40
edge_y: 30
mask_radius: 25.0
min_feature_num: 110

flow_back: true
max_square_move_dist: 1.0
min_gradient: 18.0
enable_statistics: true

# 特征与关键帧管理
reproj_err_thres: 3.0
reproj_huber_thres: 1.5
min_landmark_observations: 3
min_depth: 0.3
max_depth: 10.0
parallax_threshold: 20.0
keyframe_min_connection_ratio: 0.75

# 滑窗优化
num_iterations: 6
max_solver_time: 0.00
max_frame_count: 9
visual_factor_weight: 6.6666667
num_threads: 2

# 时间延迟可观测性
delay_obs_gyro_threshold: 0.1
delay_obs_speed_threshold: 2.0
delay_obs_min_frames: 3

# IMU 模型与积分
integrator_type: midpoint
acc_n: 0.04
acc_w: 0.00003
gyr_n: 0.001
gyr_w: 2.0e-6
g_norm: 9.81007
acc_bias: [0.0, 0.0, 0.0]
imu_repropagate_ba_threshold: 0.1
imu_repropagate_bg_threshold: 0.05

# 视觉惯性初始化
gravity_diff_threshold: 0.21
sfm_min_seed_pts: 10
sfm_min_e_inliers: 8
sfm_e_ransac_threshold: 0.004
sfm_min_pnp_pts: 10
sfm_pnp_reproj_threshold: 0.03
sfm_max_bad_pnp_ratio: 0.3
sfm_ba_max_iterations: 10
sfm_ba_num_threads: 2

# 可视化
viewer:
    path_max_poses: 4000
