#!/usr/bin/env python3
"""Generate and verify Dong-Si gravity constraint polynomial coefficients.

The constrained gravity subproblem can be written as:

    det((D - lambda I)^2 - (1 / g^2) d d^T) = 0

This script symbolically expands the sixth-order polynomial in lambda, emits
C++ code for the coefficients, and verifies the generated expression against
the determinant form with random numeric samples.
"""

from __future__ import annotations

import argparse
import math
import textwrap
from typing import Iterable

import numpy as np
import sympy as sp
from sympy.printing.c import C99CodePrinter


class _ReadableCppPrinter(C99CodePrinter):
    """C++ printer that keeps simple squares readable."""

    def _print_Pow(self, expr):  # noqa: N802 - SymPy printer hook
        base, exp = expr.as_base_exp()
        if exp == 2:
            base_code = self._print(base)
            return f"({base_code} * {base_code})"
        return super()._print_Pow(expr)


def _symbols():
    lam = sp.Symbol("lambda")
    g = sp.Symbol("g")
    d1, d2, d3 = sp.symbols("d1 d2 d3")

    D11, D12, D13 = sp.symbols("D11 D12 D13")
    D21, D22, D23 = sp.symbols("D21 D22 D23")
    D31, D32, D33 = sp.symbols("D31 D32 D33")

    D = sp.Matrix([[D11, D12, D13], [D21, D22, D23], [D31, D32, D33]])
    d = sp.Matrix([d1, d2, d3])
    return lam, g, D, d


def symbolic_coefficients() -> tuple[sp.Symbol, sp.Symbol, sp.Poly]:
    lam, g, D, d = _symbols()
    I = sp.eye(3)
    M = (D - lam * I) * (D - lam * I) - (d * d.T) / (g * g)
    poly = sp.Poly(sp.factor(sp.expand(M.det())), lam)
    return lam, g, poly


def _ccode(expr: sp.Expr) -> str:
    return _ReadableCppPrinter().doprint(expr)


def _wrap_assignment(lhs: str, rhs: str, width: int) -> list[str]:
    if len(lhs) + 1 + len(rhs) + 1 <= width:
        return [f"{lhs} {rhs};"]

    wrapped = textwrap.wrap(
        rhs,
        width=max(40, width - len(lhs) - 1),
        break_long_words=False,
        break_on_hyphens=False,
    )
    if not wrapped:
        return [f"{lhs} {rhs};"]

    lines = [f"{lhs} {wrapped[0]}"]
    indent = " " * len(lhs)
    for part in wrapped[1:]:
        lines.append(f"{indent} {part}")
    lines[-1] += ";"
    return lines


def semantic_replacements() -> list[tuple[sp.Symbol, sp.Expr]]:
    _, g, D, d = _symbols()
    replacements: list[tuple[sp.Symbol, sp.Expr]] = [
        (sp.Symbol("g2"), g * g),
        (sp.Symbol("inv_g2"), 1 / (g * g)),
    ]

    for name, expr in [
        ("d1_2", d[0] * d[0]),
        ("d2_2", d[1] * d[1]),
        ("d3_2", d[2] * d[2]),
        ("d1d2", d[0] * d[1]),
        ("d1d3", d[0] * d[2]),
        ("d2d3", d[1] * d[2]),
    ]:
        replacements.append((sp.Symbol(name), expr))

    for r in range(3):
        for c in range(3):
            name = f"D{r + 1}{c + 1}_2"
            replacements.append((sp.Symbol(name), D[r, c] * D[r, c]))

    for r1 in range(3):
        for c1 in range(3):
            for r2 in range(r1, 3):
                c2_start = c1 + 1 if r2 == r1 else 0
                for c2 in range(c2_start, 3):
                    a = D[r1, c1]
                    b = D[r2, c2]
                    name = f"D{r1 + 1}{c1 + 1}_D{r2 + 1}{c2 + 1}"
                    replacements.append((sp.Symbol(name), a * b))

    return replacements


def apply_semantic_replacements(exprs: list[sp.Expr]) -> tuple[list[tuple[sp.Symbol, sp.Expr]], list[sp.Expr]]:
    replacements = semantic_replacements()
    replaced_exprs = list(exprs)
    for symbol, expr in replacements:
        replaced_exprs = [sp.collect(sp.expand(item).subs(expr, symbol), symbol) for item in replaced_exprs]
    used = []
    for symbol, expr in replacements:
        if any(item.has(symbol) for item in replaced_exprs):
            used.append((symbol, expr))
    return used, replaced_exprs


def emit_cpp_coefficients(poly: sp.Poly, ascending: bool, cse_mode: str, width: int) -> str:
    coeffs = poly.all_coeffs()
    if ascending:
        coeffs = list(reversed(coeffs))

    lines = [
        "// Generated by scripts/generate_dongsi_gravity_coeff.py",
        "// Polynomial: det((D - lambda * I)^2 - (1 / g^2) * d * d.transpose())",
        f"Eigen::Matrix<double, {len(coeffs)}, 1> coeff;",
    ]

    if cse_mode == "full":
        replacements, reduced_coeffs = sp.cse(coeffs, symbols=sp.numbered_symbols("t"))
        for symbol, expr in replacements:
            lines.extend(_wrap_assignment(f"const double {symbol} =", _ccode(expr), width))
        coeffs = reduced_coeffs
    elif cse_mode == "semantic":
        replacements, coeffs = apply_semantic_replacements(coeffs)
        for symbol, expr in replacements:
            lines.extend(_wrap_assignment(f"const double {symbol} =", _ccode(expr), width))

    for i, coeff in enumerate(coeffs):
        expr = _ccode(coeff if cse_mode != "none" else sp.factor(coeff))
        lines.extend(_wrap_assignment(f"coeff({i}) =", expr, width))
    lines.append("return coeff;")
    return "\n".join(lines)


def expression_stats(poly: sp.Poly, ascending: bool) -> str:
    coeffs = poly.all_coeffs()
    if ascending:
        coeffs = list(reversed(coeffs))

    naive_ops = sum(sp.count_ops(coeff) for coeff in coeffs)
    replacements, reduced_coeffs = sp.cse(coeffs, symbols=sp.numbered_symbols("t"))
    cse_ops = sum(sp.count_ops(expr) for _, expr in replacements)
    cse_ops += sum(sp.count_ops(coeff) for coeff in reduced_coeffs)

    return "\n".join(
        [
            f"coefficients: {len(coeffs)}",
            f"naive operation count: {naive_ops}",
            f"cse temporary count: {len(replacements)}",
            f"cse operation count: {cse_ops}",
        ]
    )


def _polyval(coeffs_desc: Iterable[float], x: float) -> float:
    y = 0.0
    for coeff in coeffs_desc:
        y = y * x + coeff
    return y


def numeric_coefficients_from_formula(D: np.ndarray, d: np.ndarray, g: float) -> np.ndarray:
    """Build the polynomial numerically by interpolating seven samples."""
    lambdas = np.array([-3.0, -1.7, -0.4, 0.2, 1.1, 2.6, 4.0], dtype=float)
    values = []
    for lam in lambdas:
        M = (D - lam * np.eye(3)) @ (D - lam * np.eye(3)) - np.outer(d, d) / (g * g)
        values.append(np.linalg.det(M))
    values = np.array(values)
    vandermonde = np.vander(lambdas, 7, increasing=False)
    return np.linalg.solve(vandermonde, values)


def run_tests(poly: sp.Poly, num_trials: int, seed: int) -> None:
    rng = np.random.default_rng(seed)

    lam_sym, g_sym, D_sym, d_sym = _symbols()
    coeff_exprs = poly.all_coeffs()
    coeff_func = sp.lambdify(
        (
            D_sym[0, 0],
            D_sym[0, 1],
            D_sym[0, 2],
            D_sym[1, 0],
            D_sym[1, 1],
            D_sym[1, 2],
            D_sym[2, 0],
            D_sym[2, 1],
            D_sym[2, 2],
            d_sym[0],
            d_sym[1],
            d_sym[2],
            g_sym,
        ),
        coeff_exprs,
        "numpy",
    )

    worst_det_error = 0.0
    worst_coeff_error = 0.0

    for _ in range(num_trials):
        A = rng.normal(size=(3, 3))
        D = A.T @ A + 0.2 * np.eye(3)
        d = rng.normal(size=3)
        g = 9.81 + rng.normal(scale=0.05)
        args = (*D.reshape(-1), *d, g)
        coeffs = np.asarray(coeff_func(*args), dtype=float).reshape(-1)

        interp_coeffs = numeric_coefficients_from_formula(D, d, g)
        scale = max(1.0, np.linalg.norm(interp_coeffs, ord=np.inf))
        coeff_error = np.linalg.norm(coeffs - interp_coeffs, ord=np.inf) / scale
        worst_coeff_error = max(worst_coeff_error, coeff_error)

        for lam in rng.uniform(-5.0, 5.0, size=10):
            M = (D - lam * np.eye(3)) @ (D - lam * np.eye(3)) - np.outer(d, d) / (g * g)
            det_value = np.linalg.det(M)
            poly_value = _polyval(coeffs, lam)
            denom = max(1.0, abs(det_value), abs(poly_value))
            det_error = abs(poly_value - det_value) / denom
            worst_det_error = max(worst_det_error, det_error)

    print(f"verified {num_trials} random systems")
    print(f"worst determinant residual: {worst_det_error:.3e}")
    print(f"worst coefficient residual:  {worst_coeff_error:.3e}")

    if not math.isfinite(worst_det_error) or worst_det_error > 1e-8:
        raise RuntimeError("determinant verification failed")
    if not math.isfinite(worst_coeff_error) or worst_coeff_error > 1e-7:
        raise RuntimeError("coefficient verification failed")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit-cpp", action="store_true", help="print generated C++ coefficient code")
    parser.add_argument(
        "--cse",
        choices=("semantic", "full", "none"),
        default="semantic",
        help="common subexpression style for emitted C++",
    )
    parser.add_argument("--ascending", action="store_true", help="emit coeff(0) as lambda^0 instead of lambda^6")
    parser.add_argument("--width", type=int, default=120, help="line width for emitted C++")
    parser.add_argument("--stats", action="store_true", help="print expression complexity before and after CSE")
    parser.add_argument("--test", action="store_true", help="run randomized numeric verification")
    parser.add_argument("--trials", type=int, default=100, help="number of random test systems")
    parser.add_argument("--seed", type=int, default=7, help="random seed for numeric verification")
    args = parser.parse_args()

    _, _, poly = symbolic_coefficients()
    print(f"degree: {poly.degree()}")

    if args.stats:
        print(expression_stats(poly, ascending=args.ascending))

    if args.emit_cpp:
        print(emit_cpp_coefficients(poly, ascending=args.ascending, cse_mode=args.cse, width=args.width))

    if args.test:
        run_tests(poly, num_trials=args.trials, seed=args.seed)


if __name__ == "__main__":
    main()
